name: test-generate-sheet
on:
  push:
    branches:
      - beta/v*
    tags:
      - v*
  workflow_dispatch:
    inputs:
      beta-branch-or-tag-name:
        description: The name of the beta branch or tag to release
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
  
      - name: Set tag name
        id: set-tag-name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REF_NAME="${{ github.event.inputs.beta-branch-or-tag-name }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi
          echo ::set-output name=ref-name::"$REF_NAME"
          echo ::set-output name=tag-name::"${REF_NAME#beta/}"

      - name: Create Environment
        id: create-cliff-args
        shell: bash
        run: |
          # clone and vcs import repo
          sudo pip install vcstool
          # cd "${GITHUB_ACTION_PATH}"
          # git clone https://${GH_TOKEN}git@github.com/autowarefoundation/autoware.git
          # wget https://raw.githubusercontent.com/autowarefoundation/autoware/main/autoware.repos
          # cd autoware
          # mkdir src
          # vcs import src < autoware.repos
          git clone https://${GH_TOKEN}git@github.com/tier4/autoware.universe.git
          cd autoware.universe
          git checkout ${{ steps.set-tag-name.outputs.ref-name }}
          ls ../

      - name: Set target name for beta branches
        id: set-target-name
        shell: bash
        run: |
          if [[ "${{ steps.set-tag-name.outputs.ref-name }}" =~ "beta/" ]]; then
            echo ::set-output name=target-name::"${{ steps.set-tag-name.outputs.ref-name }}"
          fi

      - name: Create a local tag for beta branches
        shell: bash
        run: |
          cd autoware.universe
          if [ "${{ steps.set-target-name.outputs.target-name }}" != "" ]; then
            git tag "${{ steps.set-tag-name.outputs.tag-name }}"
          fi

      - name: Run generate-changelog
        id: generate-changelog
        uses: shmpwk/autoware-github-actions/generate-changelog@dev
        with:
          save-json-output: true
          git-cliff-config: cliff.toml
          git-cliff-args: --current --repository autoware.universe 
